liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  enabled: true
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/journals?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true