server:
  context-path: /person-api
  port: 8090

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  enabled: true
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personapi?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true